from ubuntu

maintainer Dockerfiles

run apt-get update
run apt-get install -y supervisor
run apt-get install -y build-essential
run apt-get install -y python python-dev python-setuptools python-pip
run pip install --upgrade pip

run pip install uwsgi django djangorestframework django-ipware
run apt-get install -y python-psycopg2